# Generated by Django 4.2.29 on 2026-04-05 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('search', 'Search'), ('category_filter', 'Category Filter'), ('checkout', 'Checkout')], db_index=True, max_length=30)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('search_query', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('total_views', models.IntegerField(default=0)),
                ('total_cart_actions', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('preferred_categories', models.JSONField(blank=True, default=dict)),
                ('price_range_preference', models.JSONField(blank=True, default=dict)),
                ('activity_pattern', models.JSONField(blank=True, default=dict)),
                ('behavior_cluster', models.IntegerField(blank=True, null=True)),
                ('predicted_intent', models.CharField(blank=True, choices=[('browsing', 'Browsing'), ('buying', 'Buying'), ('comparing', 'Comparing'), ('returning', 'Returning')], max_length=20, null=True)),
                ('purchase_likelihood', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userbehaviorprofile',
            constraint=models.CheckConstraint(check=models.Q(('user_id__isnull', False), ('session_id__isnull', False), _connector='OR'), name='behavior_profile_has_identifier'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['user_id', 'event_type'], name='behavior_be_user_id_8f12ac_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['session_id', 'event_type'], name='behavior_be_session_c0377b_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['user_id', 'created_at'], name='behavior_be_user_id_718b91_idx'),
        ),
    ]
