# Generated by Django 4.2.21 on 2026-04-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('product_id', models.IntegerField()),
                ('recommendation_type', models.CharField(choices=[('personalized', 'Personalized'), ('similar', 'Similar Products'), ('also_bought', 'Also Bought'), ('trending', 'Trending'), ('cart', 'Cart-Based')], max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_log',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='recommendat_user_id_656c57_idx'), models.Index(fields=['recommendation_type', 'created_at'], name='recommendat_recomme_470acf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_a_id', models.IntegerField(db_index=True)),
                ('product_b_id', models.IntegerField(db_index=True)),
                ('similarity_score', models.FloatField()),
                ('similarity_type', models.CharField(choices=[('content', 'Content-Based'), ('semantic', 'Semantic'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_similarity',
                'indexes': [models.Index(fields=['product_a_id', 'similarity_score'], name='product_sim_product_e96808_idx'), models.Index(fields=['product_b_id', 'similarity_score'], name='product_sim_product_09819c_idx')],
                'unique_together': {('product_a_id', 'product_b_id', 'similarity_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductCoOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_a_id', models.IntegerField(db_index=True)),
                ('product_b_id', models.IntegerField(db_index=True)),
                ('co_occurrence_count', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_co_occurrence',
                'indexes': [models.Index(fields=['product_a_id', 'co_occurrence_count'], name='product_co__product_808e03_idx')],
                'unique_together': {('product_a_id', 'product_b_id')},
            },
        ),
    ]
