apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET_KEY: "change-me"
  SERVICE_AUTH_TOKEN: "change-me"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change-me"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "change-me"
  NEO4J_PASSWORD: "change-me"
