# Generated by Django 4.2.21 on 2026-06-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('screen_size', models.CharField(max_length=80)),
                ('battery', models.CharField(max_length=80)),
                ('operating_system', models.CharField(max_length=120)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_details', to='products.product')),
            ],
            options={
                'db_table': 'mobile_products',
            },
        ),
        migrations.CreateModel(
            name='ComputerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120)),
                ('ram', models.CharField(max_length=80)),
                ('storage', models.CharField(max_length=120)),
                ('cpu', models.CharField(max_length=160)),
                ('screen_size', models.CharField(max_length=80)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computer_details', to='products.product')),
            ],
            options={
                'db_table': 'computer_products',
            },
        ),
        migrations.CreateModel(
            name='ClothesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=80)),
                ('material', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=40)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_details', to='products.product')),
            ],
            options={
                'db_table': 'clothes_products',
            },
        ),
    ]
